### ISSUE TITLE
大佬这种情况怎么办

### ISSUE THREAD

**Issue by 1765766891** [opq-osc/OPQ-SetuBot#39]
ℹ️ 2021-05-05 22:00:08 INFO	开始更新所有群数据~
❌ 2021-05-05 22:00:08 ERROR	响应码出错 => 500
✔️ 2021-05-05 22:00:08 SUCCESS	更新群信息成功~
==== 当前版本为: 0.0.21, 已有最新版本: 3.1, 请及时更新! ====

**Comment by yuban10703** [comment]
你OPQ的端口对么

**Comment by 1765766891** [comment]
恩

**Comment by yuban10703** [comment]
OPQ的bot登录了么...

**Comment by 1765766891** [comment]
啊，我傻逼了、、、
