### ISSUE TITLE
Lolicon API使用问题

### ISSUE THREAD

**Issue by Alex-Lu-hub** [opq-osc/OPQ-SetuBot#40]
如果不翻墙的话，输入“来张色图”没有任何反馈，查看日志为

> ℹ️ 06-06 23:34:20 INFO   从本地数据库获取到0张关于[]的setu  实际发送0张
>^C⚠️ 06-06 23:34:39 WARNING      Disconnected to the serve!
>bye~
>⚠️ 06-06 23:34:46 WARNING        响应超时，但不代表处理未成功, 结果未知! => timed out
>ℹ️ 06-06 23:34:46 INFO   从loliconのapi获取到1张关于[]的set 实际发送1张

翻墙的话，输入“来张色图”反馈一直为”你的xp好奇怪哦“，查看日志为

>ℹ️ 06-06 23:35:52 INFO   从本地数据库获取到0张关于[]的setu  实际发送0张
>⚠️ 06-06 23:35:52 WARNING        api1 boom~ :check_hostname requires server_hostname

**Comment by Alex-Lu-hub** [comment]
翻墙采取的是export http_proxy和https_proxy，先配置这个，再运行的程序

**Comment by yuban10703** [comment]
不要给PY代理......

**Comment by yuban10703** [comment]
超时可能是因为图片下载太慢了.....

**Comment by Alex-Lu-hub** [comment]
那超时有什么解决方案呢。日志里写着发送了一张，但是实际上也没有在群里发出来

**Comment by yuban10703** [comment]
你看看opq的日志，有没有图片上传的log

**Comment by Alex-Lu-hub** [comment]
没有图片上传的日志，但有如下报错日志
> 2021/06/07 00:03:52.182 [E]  QQLuaHttpVmRun 
> /home/lighthouse/DOTA2bot/OPQBot_6.0.12_linux_amd64/WebPlugins/Api_LuaCaller.lua:196: context deadline exceeded stack traceback:
>         /home/lighthouse/DOTA2bot/OPQBot_6.0.12_linux_amd64/WebPlugins/Api_LuaCaller.lua:196: in main chunk
>        [G]: ?
> 2021/06/07 00:03:52.182 [M]  POST       /v1/LuaApiCaller?funcname=SendMsg&qq=934547176&timeout=20    30.002897492s

**Comment by yuban10703** [comment]
应该是opq没走到代理，图片下载超时了

**Comment by Alex-Lu-hub** [comment]
这次我在OPQ的tty下export http_proxy和https_proxy开启代理，在setuBot的tty下没有开启代理（通过wget google验证过）。得到的报错信息如下：

>3⚠️ 06-07 00:17:52 WARNING        api1 boom~ :HTTPSConnectionPool(host='api.lolicon.app', port=443): Read timed out. (read timeout=8)

**Comment by yuban10703** [comment]
这次是api超时了。。。

**Comment by Alex-Lu-hub** [comment]
那估计是因为我在OPQ所在的tty开代理后，OPQ所对应的API地址变了嘛。。。。。。这该咋整

**Comment by yuban10703** [comment]
不是，是lolicon的api超时了，和opq无关。。

**Comment by yuban10703** [comment]
你多试试 这个api偶尔挺卡

**Comment by Alex-Lu-hub** [comment]
所以这个api超时问题，不需要给setubot的tty开代理是吗？（毕竟来代理直接提示check_hostname requires server_hostname）

**Comment by yuban10703** [comment]
不用开代理。。

**Comment by Alex-Lu-hub** [comment]
OPQ tty开启了代理，setubot未开启代理，然后我在python包里将timeout从20改为了60。现象是每次到了30s左右就会结束post的任务，二者输出如下。

OPQ
> 2021/06/07 01:21:59.488 [M]  POST       /v1/LuaApiCaller?funcname=SendMsg&qq=934547176&timeout=60    30.004271111s

setubot
> ❌ 06-07 01:21:59 ERROR  返回为null, 该类情况多数是因为响应超时或者该API不存在，或服务端操作超时(此时不代表未成功)

看着像是下不下来图片？

**Comment by Alex-Lu-hub** [comment]
重新确保代理的情况下运行OPQ，现象相同，区别在于OPQ的反应时间更快了，不是30s，而是 146.524us 。有怀疑过是不是我的lolico key错误，但是再三确认key无误。。。。。。确实想不通到底是哪里的问题了。

**Comment by yuban10703** [comment]
你手动发下P站的图片试试

**Comment by yuban10703** [comment]
https://i.pximg.net/c/540x540_70/img-master/img/2020/06/22/19/00/06/82496519_p0_master1200.jpg
