### ISSUE TITLE
502响应码出错

### ISSUE THREAD

**Issue by kokorousaki** [opq-osc/OPQ-SetuBot#42]
![image](https://user-images.githubusercontent.com/87707351/126427884-e751ef09-7932-425b-b1c9-66bb30e9fbd9.png)
启动bot.py程序后，对机器发送命令，返回502报错，啥原因呀？

**Comment by yuban10703** [comment]
你botoy.json里的机器人QQ有没有填错

**Comment by kokorousaki** [comment]
![image](https://user-images.githubusercontent.com/87707351/126429143-80444d4c-d182-4630-9f9b-78347f65e099.png)
这样填的没错吧

**Comment by yuban10703** [comment]
感觉像代理的问题,我本地开代理后会503

**Comment by kokorousaki** [comment]
> 感觉像代理的问题,我本地开代理后会503

curl P站和谷歌是没问题的
我用的sslocal，socket5代理的(1080端口)，然后用provixy代理这个socket5（8118）端口

**Comment by yuban10703** [comment]
你看看OPQ那有没有收到API请求

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/126429629-1dc97341-f135-416c-9506-db88ec7e75e1.png)
会有这种日志

**Comment by kokorousaki** [comment]
> ![image](https://user-images.githubusercontent.com/39484884/126429629-1dc97341-f135-416c-9506-db88ec7e75e1.png)
> 会有这种日志

![image](https://user-images.githubusercontent.com/87707351/126429828-44d94390-9b74-4c4e-bc61-3249d212af11.png)
是这个吗 我看的nohup的日志

**Comment by yuban10703** [comment]
不是,是我打码的那条

**Comment by kokorousaki** [comment]
.../OPQBot_6.0.20_linux_amd64/Logs下有个OPQBot.2021-07-21.001.log
不过一直没更新了，时间是凌晨的了，最后一条信息是8888端口被占用，后面解决了，面板是可以打开的

**Comment by kokorousaki** [comment]
> 不是,是我打码的那条
> POST开头的那个

那个在哪个文件看的

**Comment by yuban10703** [comment]
OPQ运行的日志啊...

**Comment by yuban10703** [comment]
实时打印的

**Comment by kokorousaki** [comment]
> 实时打印的

除了心跳成功和我刚才发图片那种就没啦

**Comment by yuban10703** [comment]
那就是请求没发到OPQ那,你运行起来后关掉本地的代理试试

**Comment by kokorousaki** [comment]
> 那就是请求没发到OPQ那,你运行起来后关掉本地的代理试试

![image](https://user-images.githubusercontent.com/87707351/126430729-f5394453-c2c3-4893-9c80-e597a92e83c0.png)
guan'l
关了请求报错orz

**Comment by kokorousaki** [comment]
botoy.json的host地址只能填127吗，我填局域网IP貌似不行

**Comment by yuban10703** [comment]
局域网可以的

**Comment by kokorousaki** [comment]
> > 那就是请求没发到OPQ那,你运行起来后关掉本地的代理试试
> 
> ![image](https://user-images.githubusercontent.com/87707351/126430729-f5394453-c2c3-4893-9c80-e597a92e83c0.png)
> guan'l
> 关了请求报错orz

连回去发送sysinfo再次报这个错
ERROR	响应码出错 => 502

**Comment by kokorousaki** [comment]
> 局域网可以的

我貌似知道原因了 我先试下哈哈
