### ISSUE TITLE
在发送色图时出现错误

### ISSUE THREAD

**Issue by TeoZler** [opq-osc/OPQ-SetuBot#43]
使用python版本：python3.8.10
使用系统版本：WSL ubuntu 20.04LST
使用OPQBOT版本：v6.0.20

插件报错如下

ℹ️ 07-27 01:15:28 INFO   GroupMsg ->  {'FromGroupId': xxxxxxxxxxxx, 'FromGroupName': 'xxxxxx', 'FromUserId': xxxxxxx, 'FromNickName': 'xxxxxxxxxx', 'Content': '来点ppc色图', 'MsgType': 'TextMsg', 'MsgTime': 1627319727, 'MsgSeq': 2041, 'MsgRandom': 3826924990, 'RedBaginfo': None}
✔️ 07-27 01:15:29 SUCCESS        群:xxxxxxx 从API:Lolicon获取到关于['ppc']的色图0张,去除600s内重复发送过的后剩余0张
✔️ 07-27 01:15:30 SUCCESS        群:xxxxxxx 从API:Yuban获取到关于['ppc']的色图0张,去除600s内重复发送过的后剩余0张
✔️ 07-27 01:15:30 SUCCESS        群:xxxxxxx 从API:Pixiv获取到关于['ppc']的色图1张,去除600s内重复发送过的后剩余1张
❌ 07-27 01:15:52 ERROR 响应码出错 => 500

OPQBOT报错如下

2021/07/27 01:19:14.075 [C]  Api_LuaCaller FuncName SendMsg

2021/07/27 01:19:20.145 [D]  User xxxxxxxx 心跳成功 time:2021年07月27日 01时19分20秒
2021/07/27 01:19:35.399 [E]  QQLuaHttpVmRun /home/OPQBot_6.0.20_linux_amd64/WebPlugins/Api_LuaCaller.lua:196: context deadline exceeded
stack traceback:
        /home/OPQBot_6.0.20_linux_amd64/WebPlugins/Api_LuaCaller.lua:196: in main chunk
        [G]: ?
2021/07/27 01:19:35.399 [M]  POST       /v1/LuaApiCaller?funcname=SendMsg&qq=xxxxxxxxxxxx&timeout=20      21.3311142s

**Comment by yuban10703** [comment]
这个貌似是超时了,可能是上行太慢了?

**Comment by yuban10703** [comment]
你配置了代理?还是机子本来就能上Pixiv?
如果配置了代理的话,需要把/plugins/bot_Setu/config.json里面的false改成true

**Comment by TeoZler** [comment]
是代理设置的问题，解决了，谢谢dalao
