### ISSUE TITLE
考虑加入反和谐功能吗

### ISSUE THREAD

**Issue by test-black** [opq-osc/OPQ-SetuBot#44]
手机偶尔会有一部分图不能正常显示，PC端（）则是都不显示
![image](https://user-images.githubusercontent.com/28062894/128684500-5fe8eb26-034c-440b-a0ac-fee6c7ee784a.png)

![image](https://user-images.githubusercontent.com/28062894/128684371-fbcf697b-c446-4a09-bbf3-4f7c2e09de53.png)

**Comment by yuban10703** [comment]
这个可能是风控了

**Comment by yuban10703** [comment]
你再挂几天试试会不会正常,不行的话就加个反和谐....

**Comment by test-black** [comment]
![image](https://user-images.githubusercontent.com/28062894/128703601-1383b215-25c4-4294-9452-f7be11f76d74.png)
过风控时间了

**Comment by yuban10703** [comment]
风控不确定的,你电脑上所有的图都看不到?..

**Comment by test-black** [comment]
10张显示1张这个样子

**Comment by yuban10703** [comment]
那是正常的......

**Comment by test-black** [comment]
PC是有什么特别的限制吗，不管是TIM还是QQ都是这个情况

**Comment by yuban10703** [comment]
母鸡,电脑裂个一两张图正常...
