### ISSUE TITLE
色图请求失败

### ISSUE THREAD

**Issue by Baozixian** [opq-osc/OPQ-SetuBot#45]
![image](https://user-images.githubusercontent.com/68880075/130239335-b8755c66-694f-49b2-b156-6257ddc13f43.png)
![image](https://user-images.githubusercontent.com/68880075/130239358-f8dbf456-5f16-4a65-8f3c-436b4ebe2ed5.png)
如图，搜图功能正常，pixiv密钥更新也正常

**Comment by yuban10703** [comment]
看日志好像没什么问题,响应超时指的是OPQ那里
