### ISSUE TITLE
小白想请教如何配置proxies代理

### ISSUE THREAD

**Issue by seraphpant** [opq-osc/OPQ-SetuBot#47]
"proxies_http": {},
  "proxies_socks": "",
科学上网使用的直接购买机场主搭好的，直接在V2rayN订阅上外网，就卡在填写这两个代理
![34O `@Y5L$6V0~0N6S9$}NV](https://user-images.githubusercontent.com/55911958/132948310-6d3f9c7a-9312-4ced-a77b-1878dd764fb4.png)
其他的地方例如pixiv_token谷歌解决好，saucenao的api也是解决好，实在是搞不懂代理的问题。

**Comment by yuban10703** [comment]
推荐用socks代理,一般机场应该没有socks代理吧

**Comment by yuban10703** [comment]
你这个软件左下角就有socks代理

**Comment by yuban10703** [comment]
socks5://127.0.0.1:10808

**Comment by seraphpant** [comment]
按照你的提示，还是出现了无法连接的问题
![image](https://user-images.githubusercontent.com/55911958/132949629-9f4af4f6-2925-4d0b-83ad-473bf8fb4a25.png)
![image](https://user-images.githubusercontent.com/55911958/132949622-41d749f1-d3a8-4141-9bd7-76efa67b0642.png)
虽然失败了，还是感激

**Comment by yuban10703** [comment]
这个错误可能是因为开启了代理....

**Comment by yuban10703** [comment]
你关掉你v2rayN的系统代理(不是关掉软件),应该就可以了

**Comment by seraphpant** [comment]
![image](https://user-images.githubusercontent.com/55911958/132950277-508e7102-0831-425a-99f9-db406dd02c89.png)
![image](https://user-images.githubusercontent.com/55911958/132950282-2b4b8733-aaee-425e-8ee5-29ba2bfe62e8.png)
![image](https://user-images.githubusercontent.com/55911958/132950297-bec3d52a-2ced-4609-b12e-8ef51f47143c.png)
按照你的提示关闭了代理，还是会出现无法连接的问题，试过参数设置中http代理的每个选项也是如此。关闭软件也是无法连接
![image](https://user-images.githubusercontent.com/55911958/132950311-2ad8ff05-bd58-4110-8a78-fab18e6539a0.png)

**Comment by yuban10703** [comment]
emmm,那就不清楚了...你关掉V2rayn能正常连上bot的吧?

**Comment by seraphpant** [comment]
没有，原来关掉也连接不了

**Comment by yuban10703** [comment]
关掉也不能连接的话就不清楚了,你OPQBot正常么....

**Comment by seraphpant** [comment]
感谢您的帮助，最后重启了电脑后，然后再运行bot和插件，已经能够使用了
