### ISSUE TITLE
ImportError: cannot import name 'async_decorators' from 'botoy'

### ISSUE THREAD

**Issue by test-black** [opq-osc/OPQ-SetuBot#49]
![image](https://user-images.githubusercontent.com/28062894/133298558-1dfcbd2e-37f7-4321-bd9a-f79c042c2a61.png)

**Comment by yuban10703** [comment]
没更新botoy吧

**Comment by yuban10703** [comment]
pip install botoy -i https://pypi.org/simple --upgrade

**Comment by test-black** [comment]
这个 botoy 更新太频繁了

**Comment by xiyaowong** [comment]
> 这个 botoy 更新太频繁了

botoy很早的更新就注意兼容了。真正原因是这个项目的更新也频繁
