### ISSUE TITLE
@

### ISSUE THREAD

**Issue by weijunshaoman** [opq-osc/OPQ-SetuBot#51]
为什么@机器人就无法发图呢

**Comment by yuban10703** [comment]
本来就没做@的支持呀。。。

**Comment by weijunshaoman** [comment]
这样吗，孩子是新手，不太理解，打扰了，我自己看下如何做@的功能吧，谢谢答复





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 晚上11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [opq-osc/OPQ-SetuBot] @ (Issue #51)





 
本来就没做@的支持呀。。。
