### ISSUE TITLE
开启代理和设置 base64 为 true 时报错

### ISSUE THREAD

**Issue by test-black** [opq-osc/OPQ-SetuBot#53]
![Snipaste_2021-12-03_10-11-31](https://user-images.githubusercontent.com/28062894/144533096-0240bf80-ecbf-464d-be01-e82e1fd2c7a6.png)

plugins/bot_Setu/config.json
设置为 false 又总是提示无响应，挂机有一段时间了，不像是风控问题

**Comment by test-black** [comment]
OPQ 终端下配置了 export_http & https proxy，wget google 正常响应

**Comment by test-black** [comment]
issue #40 貌似也有这个问题

**Comment by test-black** [comment]
> OPQ 终端下配置了 export_http & https proxy，wget google 正常响应

OPQ 设置代理后，setubot 设置为 base 为 false 后私聊正常。群聊：终端正常不报那个响应超时，但发不出图。

**Comment by yuban10703** [comment]
你py的代理怎么设置的。。base64发图和opq的代理没关系

**Comment by yuban10703** [comment]
> > OPQ 终端下配置了 export_http & https proxy，wget google 正常响应
> 
> OPQ 设置代理后，setubot 设置为 base 为 false 后私聊正常。群聊：终端正常不报那个响应超时，但发不出图。

私聊正常，群聊超时就说明风控了，或者opq那里丢文件了，你把opq删了重新解压下试试

**Comment by test-black** [comment]
> 你py的代理怎么设置的。。base64发图和opq的代理没关系

botoy.json 设置 socks5://127.0.0.1:10808

**Comment by yuban10703** [comment]
> > 你py的代理怎么设置的。。base64发图和opq的代理没关系
> 
> botoy.json 设置 socks5://127.0.0.1:10808

日志截全看看

**Comment by test-black** [comment]
> > > 你py的代理怎么设置的。。base64发图和opq的代理没关系
> > 
> > 
> > botoy.json 设置 socks5://127.0.0.1:10808
> 
> 日志截全看看
![Snipaste_2021-12-03_15-29-57](https://user-images.githubusercontent.com/28062894/144562961-4fa66b61-43f2-40c5-9448-22c0a0545d4e.png)
![Snipaste_2021-12-03_15-30-37](https://user-images.githubusercontent.com/28062894/144562977-565602fe-e39e-405c-bf09-147e3729abff.png)
![Snipaste_2021-12-03_15-31-30](https://user-images.githubusercontent.com/28062894/144562984-e20fe5bc-2a5e-4e48-8f31-6b5a0c8af627.png)

**Comment by yuban10703** [comment]
不知道是啥问题，是最新的代码么..

**Comment by test-black** [comment]
> 不知道是啥问题，是最新的代码么..

是，刚才重新拉取了两个项目配置好，还是一样的情况

**Comment by test-black** [comment]
看了下，应该是 download_setu 那个函数 retry 超时无响应，是不是 OPQ 没有返回

**Comment by yuban10703** [comment]
> 看了下，应该是 download_setu 那个函数 retry 超时无响应，是不是 OPQ 没有返回

download那个函数和opq没关系。。
我刚刚把库都升级了，没复现。。

**Comment by test-black** [comment]
太迷惑了这个风控机制，我换个号再试试，晚点反馈

**Comment by yuban10703** [comment]
> 太迷惑了这个风控机制，我换个号再试试，晚点反馈

这个报错应该不是风控，你把库都升到最新，检查下代理是否正常。。。

**Comment by test-black** [comment]
还是报那个错误
![Snipaste_2021-12-03_16-52-07](https://user-images.githubusercontent.com/28062894/144573997-f89fd6c2-3e3e-4fbc-90b0-39e73b8a3107.png)
![Snipaste_2021-12-03_16-54-46](https://user-images.githubusercontent.com/28062894/144574105-e021da43-4bcc-4fde-bc32-ee139553e459.png)

**Comment by yuban10703** [comment]
curl --socks5 127.0.0.1:10808 https://www.google.com/
你试试....

**Comment by test-black** [comment]
> curl --socks5 127.0.0.1:10808 https://www.google.com/ 你试试....
![snipaste_20211203_201039](https://user-images.githubusercontent.com/28062894/144600671-7707109d-fce7-4944-a19f-238d411e1ec5.png)

**Comment by yuban10703** [comment]
那就奇怪了...不知道啥原因

**Comment by test-black** [comment]
这个小号估计直接进 tx 黑名单了都
![snipaste_20211203_202902](https://user-images.githubusercontent.com/28062894/144602674-d76c7258-eec9-4d49-9de3-7282d322feab.png)

**Comment by LukWang** [comment]
虽然这条已经close了，不过我这边成功复现了这个错误。
我把解决方案贴在这里。
看起来是因为async_timeout包的版本问题
![image](https://user-images.githubusercontent.com/20766338/147434098-ea9c12ed-28b3-461e-81b9-475ffe70b782.png)
async_timeout在4.0.0以上的版本有接口变动， timeout类变成了Timeout。。
我这边把retrying_async.py的调用改掉之后就可以work了
![image](https://user-images.githubusercontent.com/20766338/147435100-41421d0f-9d49-4e64-8de9-7a0503c4543f.png)

**Comment by yuban10703** [comment]
> 虽然这条已经close了，不过我这边成功复现了这个错误。 我把解决方案贴在这里。 看起来是因为async_timeout包的版本问题
> 
> ![image](https://user-images.githubusercontent.com/20766338/147434098-ea9c12ed-28b3-461e-81b9-475ffe70b782.png)
> 
> async_timeout在4.0.0以上的版本有接口变动， timeout类变成了Timeout。。 我这边把retrying_async.py的调用改掉之后就可以work了
> 
> ![image](https://user-images.githubusercontent.com/20766338/147435100-41421d0f-9d49-4e64-8de9-7a0503c4543f.png)

我把retrying-async换掉看看

**Comment by yuban10703** [comment]
应该解决了吧

**Comment by LukWang** [comment]
已经解决了，Thanks
