### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 53-56: ordinal not in range(256)

### ISSUE THREAD

**Issue by test-black** [opq-osc/OPQ-SetuBot#55]
![snipaste_20220108_112354](https://user-images.githubusercontent.com/28062894/148629920-fda6177a-af38-4750-9ba8-32c88a8ea985.png)

**Comment by yuban10703** [comment]
阿哲,怎么出现的?

**Comment by test-black** [comment]
重新克隆仓库填写配置信息，python3 bot.py，boom

**Comment by yuban10703** [comment]
什么系统

**Comment by yuban10703** [comment]
我更新所有库的版本到最新后不能复现呀....
`pip3 install -r requirements.txt --upgrade`

**Comment by test-black** [comment]
> 什么系统

Ubuntu 18.04

**Comment by test-black** [comment]
> 我更新所有库的版本到最新后不能复现呀.... `pip3 install -r requirements.txt --upgrade`

![snipaste_20220108_114449](https://user-images.githubusercontent.com/28062894/148630405-c7b73bb0-333d-49b7-b5e9-7044372ae641.png)

**Comment by test-black** [comment]
应该是这里导入字体报错了

![snipaste_20220108_114651](https://user-images.githubusercontent.com/28062894/148630445-2badfca6-0722-457d-bbeb-704eda4c492b.png)

**Comment by yuban10703** [comment]
你把对应文件和代码里的文件名改成英文试试

**Comment by test-black** [comment]
我换台机器试试，可能是终端控制台的编码有问题

**Comment by test-black** [comment]
树莓派上的版本通过 git pull 的形式更新没报错，但是新开的阿里云轻量（ubuntu 18.04）重新走一遍流程就报错了

**Comment by yuban10703** [comment]
换Ubuntu20.04试试....

**Comment by test-black** [comment]
依然报错，cmder 和 mobaxterm 终端都试过了

**Comment by yuban10703** [comment]
emm,试试装个中文字体..

**Comment by yuban10703** [comment]
寄了,找个脚本重装一个Ubuntu2004吧

**Comment by test-black** [comment]
用的萌咖那个dd脚本

**Comment by yuban10703** [comment]
阿哲,那可能没救了...,试试Debian

**Comment by test-black** [comment]
代码确定是UTF-8吗，我刚在本地新建个含中文字符的py文件，GBK编码后丢git上，传回来也是这种乱码

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/149263109-dea90784-3907-456f-a937-a13f00e5edd6.png)

是utf-8呀...

**Comment by test-black** [comment]
> emm,试试装个中文字体..

https://blog.csdn.net/weixin_39278265/article/details/119343204

**Comment by test-black** [comment]
ubuntu 20.04 的问题
