### ISSUE TITLE
涩图获取数为0

### ISSUE THREAD

**Issue by Mulsd** [opq-osc/OPQ-SetuBot#56]
QQ发送  ：来点色图
终端输出：
ℹ️ 03-05 12:55:15 INFO   Received event "OnFriendMsgs" [/]
ℹ️ 03-05 12:55:15 INFO   FriendMsg ->  {'FromUin': ---, 'ToUin': ---, 'MsgType': 'TextMsg', 'MsgSeq': 22, 'Content': '来点色图', 'RedBaginfo': None}
✔️ 03-05 12:55:15 SUCCESS        好友:--- 从API:Yuban获取到关于[]的色图1张,去除600s内重复发送过的后剩余1张
✔️ 03-05 12:55:19 SUCCESS        好友:--- 从API:Lolicon获取到关于[]的色图0张,去除600s内重复发送过的后剩余0张
✔️ 03-05 12:55:19 SUCCESS        好友:--- 从API:Pixiv获取到关于[]的色图0张,去除600s内重复发送过的后剩余0张
---
OPQBot也没有图片输出
机子在境外，应该是可以直连的，所以没有配置代理

**Comment by yuban10703** [comment]
这个是正常的,看看发送时候的OPQBot日志

**Comment by Mulsd** [comment]
OPQBot并没有发出图片
-
QQ输入 来点涩图
终端输出：
2022/03/05 01:33:16.459 [C]  
FriendParseMsg
2022/03/05 01:33:16.462 [N]  From log.lua Log

From Msg 
FromUin  ---
ToUin ---
MsgType TextMsg Content 来点涩图 MsgSeq 10553

**Comment by Mulsd** [comment]
重新部署了一遍后已解决，推测为Q群配置文件的问题。
话说那个生成配置文件的脚本不能用啊，要手动配置才行

**Comment by yuban10703** [comment]
> 重新部署了一遍后已解决，推测为Q群配置文件的问题。 话说那个生成配置文件的脚本不能用啊，要手动配置才行

不会吧,有什么报错么?

**Comment by Mulsd** [comment]
> > 重新部署了一遍后已解决，推测为Q群配置文件的问题。 话说那个生成配置文件的脚本不能用啊，要手动配置才行
> 
> 不会吧,有什么报错么?

root@sheep2:/home/Mulsd/OPQ-SetuBot/script# python3 generateConfig.py 
Traceback (most recent call last):
  File "generateConfig.py", line 14, in <module>
    action = Action(host=botConf["host"], port=botConf["port"])
  File "/usr/local/lib/python3.8/dist-packages/botoy/action.py", line 31, in __init__
    self.qq = int(qq or jconfig.qq)  # type: ignore
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by yuban10703** [comment]
botoy.json里的qq字段填机器人的qq 应该就能用了

**Comment by Mulsd** [comment]
> botoy.json里的qq字段填机器人的qq 应该就能用了

不行
root@sheep2:/home/Mulsd/OPQ-SetuBot/script# python3 generateConfig.py 
Traceback (most recent call last):
  File "generateConfig.py", line 14, in <module>
    action = Action(host=botConf["host"], port=botConf["port"])
  File "/usr/local/lib/python3.8/dist-packages/botoy/action.py", line 31, in __init__
    self.qq = int(qq or jconfig.qq)  # type: ignore
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by yuban10703** [comment]
> > botoy.json里的qq字段填机器人的qq 应该就能用了
> 
> 不行 root@sheep2:/home/Mulsd/OPQ-SetuBot/script# python3 generateConfig.py Traceback (most recent call last): File "generateConfig.py", line 14, in action = Action(host=botConf["host"], port=botConf["port"]) File "/usr/local/lib/python3.8/dist-packages/botoy/action.py", line 31, in **init** self.qq = int(qq or jconfig.qq) # type: ignore TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

更新一下,刚刚改了..

**Comment by Mulsd** [comment]
> 更新一下,刚刚改了..

您改了之后有试运行过吗？
root@sheep2:/home/Mulsd/OPQ-SetuBot/script# python3 generateConfig.py 
Traceback (most recent call last):
  File "generateConfig.py", line 11, in <module>
    with open(curFileDir.parent / "botoy.json", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'botoy.json'

如果将botoy.json放置在script里，则有：
root@sheep2:/home/Mulsd/OPQ-SetuBot/script# python3 generateConfig.py 
ℹ️ 03-05 21:28:55 INFO   开始更新所有群数据~
Traceback (most recent call last):
  File "generateConfig.py", line 99, in <module>
    with open(filePath, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'plugins/bot_Setu/database/DB/configs/428469111.json'

**Comment by yuban10703** [comment]
为什么变成相对路径了...,我这运行是正常的

再更新下,应该正常了.....

**Comment by Mulsd** [comment]
解决了，改BUG辛苦了
