### ISSUE TITLE
请问未使用base64发送色图怎么解决

### ISSUE THREAD

**Issue by a437730262** [opq-osc/OPQ-SetuBot#59]
root@VM-16-14-ubuntu:~/OPQ-SetuBot# python3 bot.py
ℹ️ 04-13 10:07:10 INFO   同步定时任务已启动
ℹ️ 04-13 10:07:10 INFO   异步定时任务已启动
✔️ 04-13 10:07:10 SUCCESS        读取.PixivToken.json成功~
ℹ️ 04-13 10:07:10 INFO   离下次刷新还有:1908s
⚠️ 04-13 10:07:10 WARNING        未使用base64发送setu

**Comment by yuban10703** [comment]
https://github.com/opq-osc/OPQ-SetuBot/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

setu.base64_send

**Comment by a437730262** [comment]
感谢帮助，已经解决了。现在在bot使用过程中出不了图，请问这样是被风控了吗
![$3WC99R(SL)~HQ H OD%H)K](https://user-images.githubusercontent.com/74000837/163088814-bc1200cd-13b8-47f2-975a-95710bd4e4c4.png)
![}IQ2G_AW`XPSFL9TE6%%`75](https://user-images.githubusercontent.com/74000837/163088893-b404340f-efc7-4b8b-9bec-ecc9e333887b.png)
[](url)

**Comment by yuban10703** [comment]
应该是风控了,等几天应该就行了

**Comment by a437730262** [comment]
OKK
