### ISSUE TITLE
大佬您好，我想请教一个问题

### ISSUE THREAD

**Issue by Fhm-newbie** [opq-osc/OPQ-SetuBot#63]
我已经安装好了这个bot，本来是能正常运行的，但是我关闭了一次之后，再运行显示cannot import name 'jconfig' from 'botoy'，能请问这个该怎么解决吗？

**Comment by yuban10703** [comment]
截个图看看..

**Comment by Fhm-newbie** [comment]
![image](https://user-images.githubusercontent.com/63446200/166861215-31cad88f-8486-4c5f-89df-102e519c8212.png)

**Comment by yuban10703** [comment]
重新安装下botoy试试..

pip3 install botoy -i https://pypi.org/simple --upgrade

**Comment by Fhm-newbie** [comment]
哦，好了，谢谢大佬
