### ISSUE TITLE
请问私聊的配置文件有吗

### ISSUE THREAD

**Issue by 1294266616** [opq-osc/OPQ-SetuBot#66]
私聊机器人发图消息太详细了想修改下找不到配置文件命令也没用是没有吗
对了有群配置是有通用配置文件吗一个个修改好累

**Comment by yuban10703** [comment]
私聊的话和群聊是一样的 
好友会话是[0.json](https://github.com/opq-osc/OPQ-SetuBot/blob/master/plugins/bot_Setu/database/DB/configs/0.json)

没有通用的配置文件

**Comment by 1294266616** [comment]
对机器人私聊要图怎么弄都没效果还是没有变化，配置文件都修改了还是没少

**Comment by yuban10703** [comment]
我看了下代码
好友会话是不能修改的
私聊显示的信息应该是和群聊一样的

**Comment by 1294266616** [comment]
可现在就是群聊的有效，私聊还是原样是任意群配置文件还是某个的？
![QQ图片20220529035054](https://user-images.githubusercontent.com/52421598/170840858-2620c147-47b7-46c5-a338-cf5edad634d0.png)

**Comment by yuban10703** [comment]
你这是好友会话吧

**Comment by 1294266616** [comment]
可是我改了好友文件也没效果

**Comment by 1294266616** [comment]
还是说机器人的无法修改吗

**Comment by yuban10703** [comment]
好友不能改....

**Comment by 1294266616** [comment]
那以后能支持吗
