### ISSUE TITLE
请问搜图功能现在是不能实现了

### ISSUE THREAD

**Issue by WhaTFS** [opq-osc/OPQ-SetuBot#72]
我在bot正常工作的情况下按照wiki进行搜图指令无反应

**Comment by yuban10703** [comment]
没反应可能是没搜到
![image](https://user-images.githubusercontent.com/39484884/185608883-143951c9-93b8-4d11-88e3-bc408010fa83.png)

**Comment by WhaTFS** [comment]
> 没反应可能是没搜到 ![image](https://user-images.githubusercontent.com/39484884/185608883-143951c9-93b8-4d11-88e3-bc408010fa83.png)

好的谢谢
