### ISSUE TITLE
请问如何降低qq账号被冻结概率

### ISSUE THREAD

**Issue by WhaTFS** [opq-osc/OPQ-SetuBot#73]
bot上线2天账号被封禁一天（哭），或者反过来问，哪些情况或操作会加大被封概率

**Comment by yuban10703** [comment]
少发色图,减少内鬼

**Comment by WhaTFS** [comment]
> 少发色图,减少内鬼

那请问如果开启撤回会不会好一点（之前我把它关了）

**Comment by yuban10703** [comment]
> > 少发色图,减少内鬼
> 
> 那请问如果开启撤回会不会好一点（之前我把它关了）

可能吧
