### ISSUE TITLE
服务端操作超时

### ISSUE THREAD

**Issue by KnightKilito** [opq-osc/OPQ-SetuBot#74]
昨晚第一次用阿里云服务器搭建完环境搞完就有反应，后面换成国外服务器跑，似乎是被风控，虽然没法发信息但是可以正常创建json配置文件
![1](https://user-images.githubusercontent.com/61006533/185969868-8b2fe22d-15d6-49a5-bfcb-d6fe4906ea96.png)
![2](https://user-images.githubusercontent.com/61006533/185969935-e10d9740-0776-4754-858c-c8c2d64a672e.png)

但是现在不仅没法发消息，连json文件也无法正常创建了
报错信息：
```
ERROR 返回为null, 该类情况多数是因为响应超时或者该API不存在，或服务端操作超时(此时不代表未成功)
```
![3](https://user-images.githubusercontent.com/61006533/185969393-0403b525-5018-41a5-81d6-3da22cc59a94.png)
我知道风控可能导致没法发消息，但是风控也会影响文件创建吗，还是说就是单纯服务端操作超时，我哪里出什么错误了（我在国外服务器配置的时候是直接copy配置文件过去的呀）

**Comment by yuban10703** [comment]
这个服务端是OPQBot,一般都是因为风控,等一段时间看看

**Comment by KnightKilito** [comment]
我超秒回

哦哦好，xxdl
