### ISSUE TITLE
在获取pixiv token时输入账号密码后发生下列报错，如何处理？账号密码均无误，且机器能ping通pixiv.net

### ISSUE THREAD

**Issue by Soupcpu** [opq-osc/OPQ-SetuBot#75]
root@ser182592997362:~/OPQ-SetuBot# docker run --rm -it eggplanter/gppt lh -u [填了账号] -p [填了密码]
Traceback (most recent call last):
  File "/usr/local/bin/gppt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 149, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 58, in func_loginh
    res = g.login(headless=True, user=ns.username, pass_=ns.password)
  File "/usr/local/lib/python3.10/site-packages/gppt/selenium.py", line 74, in login
    WebDriverWait(self.driver, 10).until(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556066ae7a23 <unknown>
#1 0x5560665b2e18 <unknown>
#2 0x5560665e9151 <unknown>
#3 0x5560665e9311 <unknown>
#4 0x55606661bec4 <unknown>
#5 0x5560666069bd <unknown>
#6 0x556066619c5b <unknown>
#7 0x556066606883 <unknown>
#8 0x5560665dc3fa <unknown>
#9 0x5560665dd4c5 <unknown>
#10 0x556066b1716d <unknown>
#11 0x556066b2d5bb <unknown>
#12 0x556066b18e75 <unknown>
#13 0x556066b2de85 <unknown>
#14 0x556066b0c86f <unknown>
#15 0x556066b48ae8 <unknown>
#16 0x556066b48c68 <unknown>
#17 0x556066b63aad <unknown>
#18 0x7ff4c08b1fa3 <unknown>

**Comment by Soupcpu** [comment]
> https://gist.github.com/upbit/6edda27cb1644e94183291109b8a5fde
> 
> 那就用这个试试

我不太常用Linux系统，不太会用这种方法查，您还有别的方法吗？或者是我把账号密码发您，您能不能帮我查一下XD

**Comment by Soupcpu** [comment]
> https://gist.github.com/upbit/6edda27cb1644e94183291109b8a5fde
> 
> 那就用这个试试

再或者我把服务器给您开放一下，您直接帮我搭一下

**Comment by kokorousaki** [comment]
可以，得加钱

**Comment by Soupcpu** [comment]
> 可以，得加钱

V50疯狂星期四XD

**Comment by yuban10703** [comment]
> > https://gist.github.com/upbit/6edda27cb1644e94183291109b8a5fde
> > 那就用这个试试
> 
> 我不太常用Linux系统，不太会用这种方法查，您还有别的方法吗？或者是我把账号密码发您，您能不能帮我查一下XD

这个在windows上就行....
