### ISSUE TITLE
安装完后没响应，想请问下是什么情况

### ISSUE THREAD

**Issue by namett** [opq-osc/OPQ-SetuBot#78]
![image](https://user-images.githubusercontent.com/45278496/216022354-75d709ea-a1ff-4127-afd0-855c32504f94.png)

**Comment by namett** [comment]
setu的配置文件是手动配置的，将GroupExample.json直接复制为群号.json

**Comment by namett** [comment]
![image](https://user-images.githubusercontent.com/45278496/216023332-f423bc58-2b89-436f-b3fc-8351921c538c.png)

**Comment by yuban10703** [comment]
是不是botoy.json的qq号没填对

**Comment by namett** [comment]
是的是的。。。谢谢！我还想问下大佬这个
![image](https://user-images.githubusercontent.com/45278496/216030249-3907fea7-2fd7-42d1-9e77-cb67199f30d9.png)

**Comment by yuban10703** [comment]
你那网络有问题?

**Comment by namett** [comment]
好的我试试嘞

**Comment by yuban10703** [comment]
yuban和lolicon是不走配置文件里的代理的

**Comment by namett** [comment]
emmm是走终端的代理吗

**Comment by yuban10703** [comment]
这2个api应该是任何网络都能访问的,不需要代理

**Comment by namett** [comment]
嗯嗯谢谢啦，我再看看那
