### ISSUE TITLE
大佬您好，遇到了尝试刷新Pixiv_token 刷新失败

### ISSUE THREAD

**Issue by ahuiji1** [opq-osc/OPQ-SetuBot#79]
![}6 EB3F3I ~U}8G)2$4F_VC](https://user-images.githubusercontent.com/70953783/217739865-4f10e8ea-98a9-4f0e-856e-a1224f49dce3.png)
![QBZK`4`%57J4)7 I@FQ$A`4](https://user-images.githubusercontent.com/70953783/217739888-d747f5d7-cc94-4e02-a6a7-f2db983315a9.png)
大佬您好，遇到了以上的问题求解答

**Comment by yuban10703** [comment]
检查代理
