### ISSUE TITLE
关于开启r18的群聊色图等级

### ISSUE THREAD

**Issue by Fhm-newbie** [opq-osc/OPQ-SetuBot#80]
大佬您好，我想请问一下，在setu.py那里，过去版本的206行，之前我修改了1为0，可以把群聊色图在开启r18的情况下默认为无r18，但我更新到最新版本后，现版本setu.py的189行，如果把1改成0，那么会导致即使我请求r18色图也会返回无r18的色图，请问这是bug吗？还是我找错地方了？

**Comment by yuban10703** [comment]
直接删掉这些应该就行了
![image](https://user-images.githubusercontent.com/39484884/218315071-4d868eed-d55f-438f-85a2-e026357ae765.png)

**Comment by Fhm-newbie** [comment]
好的，不过我刚才抱着试一试的心态，改了下面255行的色图等级，群聊色图等级也正常了。。。

**Comment by Fhm-newbie** [comment]
还有大佬我想问一下，有时候色图会出现图片发的是一个红底白×，这是我开了base64导致的吗？

**Comment by yuban10703** [comment]
图片下载失败了,画师可能把图删掉了,不影响

**Comment by Fhm-newbie** [comment]
好的，谢谢大佬
